---
layout: home
title: Analytax
tagline: "Where tax meets technology"
---

## My Promise to Readers
{: .promise }

> Everything you’ll read here comes from my own experience, thinking, and work.  
> I sometimes use AI tools to help me research, test ideas, or express them clearly — but the substance, reasoning, and perspective are entirely my own.  
>
> I’m deeply interested in data science and AI, and my work in tax provides rich opportunities for exploring meaningful, real-world applications of both.  
> This site is where I share those explorations — combining technical curiosity with practical domain expertise.  
>
> I won’t publish anything unless I understand it, believe in it, and consider it genuinely relevant to the evolving world of tax technology.
